In [ ]:
#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
import numpy as np
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
import numpy as np
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
import numpy as np
a = np.random.randint(1, 11, (5, 5), dtype=int)
print(a)

[[ 1  2  6 10 10]
 [ 6  4  5  4 10]
 [10  6  7  6  4]
 [ 8  7 10  9  5]
 [ 6  8  2  2  8]]


In [ ]:
#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
import numpy as np
a = np.random.random((4, 4))
print(a)

[[0.2662015  0.34275186 0.46077848 0.9504375 ]
 [0.57573008 0.77486101 0.48233828 0.48198393]
 [0.02102421 0.69454261 0.26361875 0.32665104]
 [0.82862138 0.88353196 0.51782084 0.47202002]]


In [ ]:
#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте
#на них поелементні операції додавання, віднімання та множення.
import numpy as np
a = np.random.randint(1, 11, (1, 5), dtype=int)
b = np.random.randint(1, 11, (1, 5), dtype=int)
print(f"\nДодавання:\n {a} \n+ \n {b} \n=\n", a+b)
print(f"\nВіднімання:\n {a} \n- \n {b} \n=\n", a-b)
print(f"\nМноження:\n {a} \n* \n {b} \n=\n", a*b)

[[ 7  2  9 10  6]]
[[ 8  5  6 10  3]]

Додавання:
 [[ 7  2  9 10  6]] 
 + 
 [[ 8  5  6 10  3]] 
=
 [[15  7 15 20  9]]

Віднімання:
 [[ 7  2  9 10  6]] 
 - 
 [[ 8  5  6 10  3]] 
=
 [[-1 -3  3  0  3]]

Множення:
 [[ 7  2  9 10  6]] 
 * 
 [[ 8  5  6 10  3]] 
=
 [[ 56  10  54 100  18]]


In [ ]:
#6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
import numpy as np
a = np.random.randint(1, 11, (7))
b = np.random.randint(1, 11, (7))
print(f"\nCкалярний добуток:\n {a} \nта \n {b} \n=\n", np.dot(a, b))


Cкалярний добуток:
 [7 9 8 3 4 4 8] 
 та 
 [2 1 5 8 2 3 2] 
=
 123


In [ ]:
#7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
import numpy as np
a = np.random.randint(1, 11, (2, 2), dtype=int)
b = np.random.randint(1, 11, (2, 3), dtype=int)
print(f"\nМноження:\n {a} \n* \n {b} \n=\n", np.dot(a, b))


Множення:
 [[6 3]
 [2 8]] 
* 
 [[ 6  6 10]
 [ 4  5  9]] 
=
 [[48 51 87]
 [44 52 92]]


In [ ]:
#8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
import numpy as np
a = np.random.randint(1, 11, (3, 3), dtype=int)
print(f"\nМатриця:\n {a} \nта її обернена матриця:\n", np.linalg.inv(a))


Матриця:
 [[5 7 8]
 [3 5 4]
 [3 5 6]] 
та її обернена матриця:
 [[ 1.25 -0.25 -1.5 ]
 [-0.75  0.75  0.5 ]
 [ 0.   -0.5   0.5 ]]


In [ ]:
#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
import numpy as np
a = np.random.random((4, 4))
print(f"\nМатриця:\n {a} \nта її транспонована матриця:\n", a.T)


Матриця:
 [[0.48016602 0.23293578 0.63766577 0.4967982 ]
 [0.86704752 0.34708968 0.52627784 0.18699801]
 [0.98983138 0.35168338 0.33956071 0.03749531]
 [0.48998758 0.23037146 0.45665424 0.57134173]] 
та її транспонована матриця:
 [[0.48016602 0.86704752 0.98983138 0.48998758]
 [0.23293578 0.34708968 0.35168338 0.23037146]
 [0.63766577 0.52627784 0.33956071 0.45665424]
 [0.4967982  0.18699801 0.03749531 0.57134173]]


In [ ]:
#10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
import numpy as np
a = np.random.randint(1, 11, (3, 4), dtype=int)
b = np.random.randint(1, 11, (4), dtype=int)
print(f"\nМноження матриці:\n {a} \nна вектор \n {b} \n=\n", np.dot(a, b))


Множення матриці:
 [[ 9  8  6  4]
 [ 2 10 10  7]
 [ 7  4  8  2]] 
на вектор 
 [7 6 3 7] 
=
 [157 153 111]


In [ ]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
import numpy as np
a = np.random.random((2, 3))
b = np.random.random((3))
print(f"\nМноження матриці:\n {a} \nна вектор \n {b} \n=\n", np.dot(a, b))


Множення матриці:
 [[0.6476887  0.63460998 0.61255972]
 [0.58911444 0.44289355 0.91591278]] 
на вектор 
 [0.47576533 0.76797365 0.40445071] 
=
 [1.04326178 0.99085238]


In [16]:
#12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
import numpy as np
a = np.random.randint(1, 11, (2, 2), dtype=int)
b = np.random.randint(1, 11, (2, 2), dtype=int)
print(f"\nМноження:\n {a} \n* \n {b} \n=\n", a * b)


Множення:
 [[ 1 10]
 [ 8  6]] 
* 
 [[ 7  3]
 [10  6]] 
=
 [[ 7 30]
 [80 36]]


In [7]:
#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
import numpy as np
a = np.random.random((2, 2))
b = np.random.random((2, 2))
print(f"\nДобуток:\n {a} \nта \n {b} \n=\n", np.dot(a, b))


Добуток:
 [[0.09717957 0.35043101]
 [0.53909767 0.66784797]] 
та 
 [[0.52983075 0.12281601]
 [0.15912462 0.55288603]] 
=
 [[0.10725092 0.20568361]
 [0.39190158 0.43545364]]


In [14]:
#14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
import numpy as np
a = np.random.randint(1, 101, (5, 5))
print(f"\nCумa елементів матриці:\n {a}\n=\n", a.sum())


Cумa елементів матриці:
 [[26 66 82 75 13]
 [15 18 17 39 52]
 [40 88 12  3 25]
 [99 47 67 64 93]
 [81  8 94 23  2]]
=
 1149


In [13]:
#15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
import numpy as np
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))
print(f"\nВіднімання:\n {a} \n- \n {b} \n=\n", a-b)


Віднімання:
 [[ 1  8 10  3]
 [ 4 10  3  1]
 [ 8  2 10 10]
 [ 4  9 10 10]] 
- 
 [[ 1  2  7  6]
 [ 6  2  7 10]
 [ 9  3  4  7]
 [ 1  1  8  3]] 
=
 [[ 0  6  3 -3]
 [-2  8 -4 -9]
 [-1 -1  6  3]
 [ 3  8  2  7]]


In [6]:
#16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
#що містить суму елементів кожного рядка матриці.
import numpy as np
a = np.random.random((3, 3))
b = np.sum(a, axis=1)
print(f"\nМатриця:\n {a} \nвектор що містить суму елементів кожного рядка матриці:\n {b} \nвектор-стовпчик:\n", b.reshape((3, 1)))


Матриця:
 [[0.32542246 0.74244681 0.14871383]
 [0.12070108 0.05629911 0.63423342]
 [0.99237274 0.1942983  0.25682979]] 
вектор що містить суму елементів кожного рядка матриці:
 [1.2165831  0.81123361 1.44350082] 
вектор-стовпчик:
 [[1.2165831 ]
 [0.81123361]
 [1.44350082]]


In [9]:
#17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
import numpy as np
a = np.random.randint(1, 11, (3, 4))
print(f"\nМатриця:\n {a} \nматриця з квадратами:\n", np.square(a))


Матриця:
 [[ 2  5 10  9]
 [ 3  7  1  5]
 [ 9  2  7  5]] 
матриця з квадратами:
 [[  4  25 100  81]
 [  9  49   1  25]
 [ 81   4  49  25]]


In [12]:
#18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
import numpy as np
a = np.random.randint(1, 51, (4))
print(f"\nВектор:\n {a} \nвектор з квадратними коренями:\n", np.square(a))


Вектор:
 [50 27 22 50] 
вектор з квадратними коренями:
 [2500  729  484 2500]
